openapi: '3.0.0'
info:
  version: 1.0.0
  title: Worker shop API
  description: Worker shop api specification doc and client.
  contact:
    email: 159030@supinfo.com
  license:
    name: "(c) Copyright 2018 Jan Socha, all rights reserved."
components:
  securitySchemes:
    bearerAuth:
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"

